#!/usr/bin/env bash

# ========== SCRIPT CONFIGS ==========
IGNOREFORMAT=(
	"_*"
	"log"
	"default"
)

TIMEFORMAT="Task completed in %3lR"

if [[ -t 1 ]] && [[ -z "${NO_COLOR:-}" ]]; then
    COLOR_RESET="\033[0m"
	COLOR_ERROR="\033[38;5;196m"
	COLOR_FUNCTION="\033[38;5;165m"
	COLOR_COMMENT="\033[38;5;229m"
	COLOR_LOG="\033[38;5;247m"
else
    COLOR_RESET=""
    COLOR_ERROR=""
    COLOR_FUNCTION=""
    COLOR_COMMENT=""
    COLOR_LOG=""
fi


# ========== TASKS ==========
fourth() {
	return 0
}

third_() { : "third?"
	return 0
}

third() { : 'third'
	log fourth "Hello world"
}

second() { : "Second"
	log third "b" && log third_ "c"
}

first() { : 'first'
	log second "a"
}


# ========== DEFAULT ==========
default() {
	log help
}


# ========== LOG + HELP ==========
log() { : "Logs function execution in pretty format"
	if [[ -z "${NO_LOG:-}" ]]; then
		local depth=0
		for func_name in "${FUNCNAME[@]}"; do
        	[[ "$func_name" == "log" ]] && ((depth++))
    	done

		local args=""
		for arg in "$@"; do
			[[ "$arg" == *" "* ]] && arg="\"$arg\""
			args+="$arg "
		done
		
		
		local prefix=$(printf "%$(( (depth - 1) * 2 ))s" "")
		printf "${COLOR_LOG}%s %s${COLOR_RESET}\n" "${prefix//  /| }+" "$args"
	fi

	"$@"
}

help() { : "Shows this help message"
	echo "Usage: $0 <task> [args]"
	echo "Tasks:"
	
	# function name is always one word without space
	local i=1
	for func_name in $(compgen -A function); do
		local skip=0

		for glob in "${IGNOREFORMAT[@]}"; do case "$func_name" in $glob) skip=1 && break ;; esac done
		[[ $skip == 1 ]] && continue

		local func_body=$(declare -f "$func_name")
		[[ "$func_body" != *": "[\'\"]*[\'\"]* ]] && func_body=""
		func_body="${func_body#*": "[\'\"]}"
		func_body="${func_body%%[\'\"]*}"
		
		printf "\t%d) ${COLOR_FUNCTION}%-12s${COLOR_RESET} ${COLOR_COMMENT}%s${COLOR_RESET}\n" "$((i++))" "$func_name" "$func_body"
	done
}


# ========== MAIN ==========
task="${1:-default}"
shift

# check if task exists
if ! (declare -F "${task}" >/dev/null); then
	printf "${COLOR_ERROR}Unknown task: %s${COLOR_RESET}\n" "${task}"
	help
	exit 127
fi

time "$task" "$@"
