#!/usr/bin/env bash
# ========================= SHELL CONFIG =========================
set -euo pipefail
shopt -s inherit_errexit 2>/dev/null || true

# ========================= SCRIPT CONFIG =========================
if [[ -t 1 ]] && [[ -z "${NO_COLOR:-}" ]]; then
    COLOR_RESET="\033[0m"
	COLOR_ERROR="\033[38;5;196m"
	COLOR_FUNCTION="\033[38;5;165m"
	COLOR_COMMENT="\033[38;5;229m"
	COLOR_LOG="\033[38;5;247m"
else
    COLOR_RESET=""
    COLOR_ERROR=""
    COLOR_FUNCTION=""
    COLOR_COMMENT=""
    COLOR_LOG=""
fi


TIMEFORMAT="Task completed in %3lR"
COMMENT_LEFT=": '"
COMMENT_RIGHT="'"
LOGFORMAT="${COLOR_LOG}+ @${COLOR_RESET}"

# ========================= LOG FUNCTION =========================
log() { : 'Logs function execution'
	if [[ -z "${NO_LOG:-}" ]]; then
		local args=""
    	for arg in "$@"; do
    	    if [[ "${arg}" =~ [[:space:]] ]]; then
    	        args+="\"${arg}\" "
    	    else
    	        args+="${arg}"
    	    fi
    	done

		echo -e "${LOGFORMAT/@/${args}}"
	fi
	"$@"
}


# ========================= YOUR TASKS =========================
_maybe() { : 'Hidden function'
	cat ./Tuskfile >/dev/null
	return 255
}

coin_toss() { : '
	Returns -1 or 1 (almost) randomly
	!!!MULTILINE COMMENT!!!
'
	_maybe
}

hello() { : 'Greets first argument'
	log echo "Hello, ${1:-World}!"
	log echo "Another hello"
}


# ========================= HELP FUNCTION =========================
help() { : 'Prints this help message'
	echo "Usage: $0 <task> <args>"
	echo "Tasks:"

	local i=1
	for func_name in $(compgen -A function); do
		[[ "${func_name}" == _* || "${func_name}" == log ]] && continue
		local body
		body=$(declare -f "${func_name}")
		[[ "${body}" != *"${COMMENT_LEFT}"*"${COMMENT_RIGHT}"* ]] && body=""
		body="${body#*"${COMMENT_LEFT}"}"
		body="${body%%"${COMMENT_RIGHT}"*}"
		printf "\t%d) ${COLOR_FUNCTION}%-12s${COLOR_RESET} ${COLOR_COMMENT}%s${COLOR_RESET}\n" "${i}" "${func_name}" "${body}"
		((i++)) || true
	done
}



# ========================= TASK EXECUTION =========================
task=${1:-help}
shift || true

if (! declare -F "${task}" >/dev/null); then
	echo -en "${COLOR_ERROR}"
	echo -n "Unknown task: ${task}"
	echo -e "${COLOR_RESET}"
    help
    exit 1
fi

time ${task} "$@"
